### ISSUE TITLE
Test for names of htmlwidget object fails due to additional fields added in v0.6

### ISSUE THREAD

**Issue by jjallaire** [MangoTheCat/radarchart#1]
This test checks to see that the object returned from `htmlwidgets::createWidget` (via `chartJSRadar`) has the expected set of names:

https://github.com/MangoTheCat/radarchart/blob/master/tests/testthat/test-chartJSRadar.R#L13-L16

The names of the list elements of objects of class "htmlwidgets" is however an implementation detail and will change from release to release. In version 0.6 of htmlwidgets we added a `jsHooks` member to this list as seen here:

https://github.com/ramnathv/htmlwidgets/blob/master/R/htmlwidgets.R#L278-L290

The test is failing because it's seeing the `jsHooks` list member and doesn't expect to. I think that this part of the test should be removed as it's essentially inspecting an implementation detail (members of a list) and expecting it to stay constant over time.

**Comment by dougmet** [comment]
Thanks for the heads up on the failing test. I was finding it tough finding a way to check that a js plot was basically working as expected. It could be loosened a little (check that at least those names are in) using `%in%` type checks. But agree that generally chasing after changes in htmlwidgets is not ideal.

**Comment by dougmet** [comment]
For now I think we'll remove it and think of a stronger test later.

**Comment by jjallaire** [comment]
Thanks! 

This came up when submitting a new version of `htmlwidgets` to CRAN earlier today. CRAN maintainers have asked me to request that you re-submit `radarchart` with the updated (passing) tests.

**Comment by dougmet** [comment]
Great, thanks for passing this on. Duly resubmitted and updated on CRAN.
