### ISSUE TITLE
Dynamic UI doesn't work with radarcharts

### ISSUE THREAD

**Issue by jgolinkoff** [MangoTheCat/radarchart#31]
I'm trying to build a Shiny app that has a dynamic UI and uses radarcharts. I love the radarchart html-widget but unfortunately, I'm running into some trouble! For non-dynamic UIs, the radarchart widget works fine. However, for a dynamically named radarchart, I can't get anything to draw.  Sample code to reproduce the problem is below.  I have used raw HTML instead of the actual chartJSradarOutput() when rendering the UI since the output function seemed to be missing some elements.

Thanks in advance for your help with this and all of your efforts to build this package!

ui.R:

``` R
library(shiny)
library(radarchart)

shinyUI(
  fluidPage(
    div(class="container",
    h5(class="text-center", "These work because chartJSRadarOutput is specified in UI.R"),
    fluidRow(
      column(4,
             chartJSRadarOutput("Area_RadarChart_1", height=200, width=200)
      ),
      column(4,
             chartJSRadarOutput("Perimeter_RadarChart_1", height=200, width=200)
      ),
      column(4,
             chartJSRadarOutput("Orientation_RadarChart_1", height=200, width=200)
      )
    ),
    hr(),
    fluidRow(
      h5(class="text-center", "I want to display some radar charts dynamically here:"),

      strong("Attempt 1: using renderChartJSRadar directly"),
      fluidRow(
        column(2, "Result: "),
        uiOutput("dynamicRadarChartOutput_1")
      ),
      hr(),
      strong("Attempt 2: initializing a canvas element with the correct id first then using renderChartJSRadar"),
      fluidRow(
        column(2, "Result: "),
        uiOutput("dynamicRadarChartOutput_2")
      )
    ),
    hr()
    )
  )
)
```

server.R

``` R
# Example to test dynamically creating chartJSRadar elements.
shinyServer(
  function(input, output, session) {
    labs <- c("Communicator", "Data Wangler", "Programmer", "Technologist",  "Modeller", 
              "Visualizer")
    varNames = c("Area", "Perimeter", "Orientation", "CentroidX", "CentroidY", "MinInt")

    scorel = lapply(1:6, function(i){
      set.seed(i)
      data.frame("Rich" = runif(6,0,10),
                 "Andy" = runif(6,0,10),
                 "Aimee" = runif(6,0,10))
    })


    # This works great.
    lapply(1:3, function(i){
      output[[paste0(varNames[i], "_RadarChart_1")]] = renderChartJSRadar({
        chartJSRadar(scores=scorel[[i]], labs=labs, showToolTipLabel = TRUE, addDots = FALSE,
                     labelSize = 7)
      })
    })


    # Adding charts dynamically doesn't work....

    # Attempt 1:
    output$dynamicRadarChartOutput_1 = renderChartJSRadar({
      chartJSRadar(scores=scorel[[1]], labs=labs, maxScale=10, labelSize = 6, lineAlpha = .2)
    })

    # Attempt 2: 
    # First initialize a div with the correct id
    output[["dynamicRadarChartOutput_2"]] = renderUI({
      paste0("<div class='col-10'>",
            "<h5>canvas id = dynamicRadarChartOutput_2_canvas</h5>",
            "<canvas id='dynamicRadarChartOutput_2_canvas'class='chartJSRadar html-widget html-widget-output shiny-bound-output' width='200' height='200' style='visibility: inherit; width: 200px; height: 200px;'></canvas>",
            "</div>")
    })

    # Now that we have a canvas with id = dynamicRadarChartOutput_2_canvas, try and render the
    # radar chart onto it
    output[["dynamicRadarChartOutput_2_canvas"]] = renderChartJSRadar({
      chartJSRadar(scores=scorel[[2]], labs=labs, maxScale=10, labelSize = 6, lineAlpha = .2)
    })

  }  
)
```

**Comment by timelyportfolio** [comment]
This is a fairly easy fix to re-render in dynamic context.  I can try to lump in with pull #30.    The harder solution is to animate new data/chart.

**Comment by jgolinkoff** [comment]
Thanks @timelyportfolio! At this point, seeing the radar charts on the app would make me very happy - with or without animations.

**Comment by timelyportfolio** [comment]
@jgolinkoff, just getting a complete look at your code, and I now realize this is an issue completely separate from what I originally thought.  So, in terms of what I originally thought, pull #30 will now use Chart.js api to animate and update new dynamic data.  In terms of dynamically adding `htmlwidgets`, I am not sure there is a clean way to go about this.  I'm trying to remember any examples that I might have seen.  I'll play a bit and report back, but I don't think this is a `radarchart`-problem.

Perhaps it would be useful for me to more thoroughly understand the use case you are trying to achieve here.

**Comment by jgolinkoff** [comment]
Basically - I need to be able to modify the UI depending on the data the user selects to display. If, for a simple example, the user selects a variable to group on with 3 unique factors, I would want 3 separate radar charts to be displayed for these factors. I have looked around for other radar chart / spider chart implementations and the `radarchart` implementation is not only performant but the most visually appealing so that's why I was hoping to use this approach.

**Comment by timelyportfolio** [comment]
Ok, so this is a simple "working" version that I think gets us closer, and this approach should in general work for any `htmlwidget`.  I'll iterate through a bit, but I thought I would go ahead and demo while you're online :)  I will cc @ramnathv and @jcheng5 just in case (likely) they have better ideas.

```
library(shiny)
library(radarchart)

ui <- fluidPage(
  fluidRow(
    column(2, "Result: "),
    uiOutput("d1")
  )
)

# Example to test dynamically creating chartJSRadar elements.
server <- function(input, output, session) {
  labs <- c("Communicator", "Data Wangler", "Programmer", "Technologist",  "Modeller", 
            "Visualizer")
  varNames = c("Area", "Perimeter", "Orientation", "CentroidX", "CentroidY", "MinInt")

  scorel = lapply(1:6, function(i){
    set.seed(i)
    data.frame("Rich" = runif(6,0,10),
               "Andy" = runif(6,0,10),
               "Aimee" = runif(6,0,10))
  })

  # Attempt 2: 
  # First initialize a div with the correct id
  output$d1 <- renderUI({
    column(10,chartJSRadarOutput('radar1'))
  })

  output$radar1<-renderChartJSRadar({
    chartJSRadar(scores=scorel[[2]], labs=labs, maxScale=10, labelSize = 6, lineAlpha = .2)
  })
}

shinyApp(ui,server)
```

**Comment by timelyportfolio** [comment]
A very small note, `_` work in CSS id, but they are technically not allowed.  I don't think it causes problems generally but might result in some edge case bugs.

**Comment by timelyportfolio** [comment]
An illustration of the "issue" I first thought we are trying to solve in case someone wants to see, here is an example of `chartJSRadar` and its ability to handle dynamic data without complete re-render.  This is a very nice feature with `chart.js v2` that we often don't encounter with other JS libraries.

```
library(shiny)
library(radarchart)

ui <- fluidPage(
  fluidRow(
    column(2, "Result: "),
    chartJSRadarOutput('radar1')
  )
)

# Example to test dynamically creating chartJSRadar elements.
server <- function(input, output, session) {
  labs <- c("Communicator", "Data Wangler", "Programmer", "Technologist",  "Modeller", 
            "Visualizer")
  varNames = c("Area", "Perimeter", "Orientation", "CentroidX", "CentroidY", "MinInt")


  output$radar1<- renderChartJSRadar({
    invalidateLater(3000,session)
    scorel = lapply(1:6, function(i){
      data.frame("Rich" = runif(6,0,10),
                 "Andy" = runif(6,0,10),
                 "Aimee" = runif(6,0,10))
    })
    chartJSRadar(scores=scorel[[2]], labs=labs, maxScale=10, labelSize = 6, lineAlpha = .2)
  })
}

shinyApp(ui,server)
```

**Comment by jcheng5** [comment]
I don't fully follow the discussion here, but going back to the original example:

``` r
ui:
uiOutput("dynamicRadarChartOutput_1")

server:
output$dynamicRadarChartOutput_1 = renderChartJSRadar({
  chartJSRadar(scores=scorel[[1]], labs=labs, maxScale=10, labelSize = 6, lineAlpha = .2)
})
```

This doesn't work because of the mismatch between `uiOutput` and `renderChartJSRadar`; the `xxxOutput` and `renderXXX` that share an ID need to work together. Here's the proper server call:

``` r
output$dynamicRadarChartOutput_1 = renderUI({
  tagList(chartJSRadar(scores=scorel[[1]], labs=labs, maxScale=10, labelSize = 6, lineAlpha = .2))
})
```

The `tagList` (or alternatively, `htmltools::as.tags`) is needed to coerce the htmlwidget into an htmltools UI object. (I'm always surprised that `renderUI` doesn't do this automatically; perhaps that's what bit you originally too.) You don't need to limit yourself to returning a single `chartJSRadar` here, either; you can have a single `renderUI` that returns a `tagList` that wraps several widgets (of any kind).

This method (`renderUI` returning a chart or charts) works but replaces the entire chart every time something changes, I guess this is what @timelyportfolio was concerned about. If what you want to do is dynamically insert one or more radar plots whose contents are reactive and smoothly transition, then you have two options:

Option 1 - If you want to repeatedly _replace_ a set of radar charts, then use `uiOutput`/`renderUI` and have `renderUI` return a `tagList` of `chartJsRadarOutput`.

``` r
output$radarCharts <- renderUI({
  tagList(
    lapply(1:length(dims), function(i) {
      output[[paste0("radar", i)]] <- renderChartJsRadar({
        chartJSRadar(...)
      })
      chartJsRadarOutput(paste0("radar", i))
    })
  )
```

Option 2 - If you want to add and remove charts instead of replacing all of them, then set up a Shiny observer that uses `insertUI`/`removeUI` (requires GitHub version of Shiny) to add and remove `chartJsRadarOutput`s.

``` r
observeEvent(input$addCharts, {
  output[[paste0("radar", i)]] <- renderChartJsRadar({
    chartJSRadar(...)
  })
  insertUI("container", "beforeEnd",
    chartJsRadarOutput(paste0("radar", i))
  )
})
```

**Comment by jgolinkoff** [comment]
Thank you @jcheng5! It seems this wasn't a `radarchart` issue but a more specific issue with my understanding of how `renderUI` works. I added the `tagList` function as you suggested instead of trying to build the UI by pasting elements together and now the radar charts are displaying correctly!

**Comment by timelyportfolio** [comment]
Some additional discussion of dynamically adding plotly `htmlwidgets` is [here](http://community.plot.ly/t/plotly-shiny-reactive-height-of-plots/1503/8) in case someone wants to see another example..

**Comment by timelyportfolio** [comment]
@jcheng5 was about to file issue over on `shiny` to auto-tag in `renderUI`, but thought should ask first if even an option.  Looking at code, seems fairly straightforward, but have stupidly said that way too many times.
