### ISSUE TITLE
Choosing the columns in the Shiny app

### ISSUE THREAD

**Issue by NeuralPensieve** [MangoTheCat/radarchart#32]
How can I choose the columns, say `skills` in your example, in the Shiny app? Basically, I want another sideBarPanel to choose the columns.

**Comment by dougmet** [comment]
This isn't really a radarchart issue, more of a Shiny problem. However, this works for me:

``` r
# ui.R

library(radarchart)

shinyUI(pageWithSidebar(
  headerPanel('Radarchart Shiny Example'),
  sidebarPanel(
    checkboxGroupInput('selectedPeople', 'Who to include', 
                       names(radarchart::skills)[-1], selected="Rich"),
    checkboxGroupInput('selectedSkills', 'What to include', 
                       as.character(radarchart::skills$Label),
                       selected=as.character(radarchart::skills$Label))
  ),
  mainPanel(
    chartJSRadarOutput("radar", width = "450", height = "300"), width = 7
  )
))

# server.R
library(radarchart)

shinyServer(function(input, output) {
  output$radar <- renderChartJSRadar({

    chartJSRadar(skills[match(input$selectedSkills, skills$Label), c("Label", input$selectedPeople)], 
                 maxScale = 10, showToolTipLabel=TRUE)
  })
})
```

**Comment by NeuralPensieve** [comment]
Thanks a lot. This worked for me. But for some reason, when some of the skills were checked off, and I hover my mouse over the plot, it started adding them back to the plot, making the plot very jittery. Do you see this too?

**Comment by tcash21** [comment]
I have seen this behavior with the `feature-v1api` branch.

gist here: https://gist.github.com/tcash21/9b102819c0dec216866fb08d019c5d12

**Comment by NeuralPensieve** [comment]
Is there a way to fix it?

**Comment by dougmet** [comment]
Thanks for the gist. I get the same the problem, looks like a bug somewhere. It looks like the hover-over data is not being properly updated. Will investigate.

**Comment by dougmet** [comment]
Moved jittering discussion to #34
