### ISSUE TITLE
Add color legend to Shiny app

### ISSUE THREAD

**Issue by NeuralPensieve** [MangoTheCat/radarchart#33]
Is there a way to add dynamic color legend to the Shiny app?

**Comment by dougmet** [comment]
I'm not really sure what you mean by dynamic. Any option to the `chartJSRadar` function can be made to respond to a reactive. The new version (still in dev) will make legends a little easier as the chart.js API has improved a lot. The current release uses chart.js-v1 but the dev uses v2

**Comment by dougmet** [comment]
This was fixed in the v0.3.1 release. Let me know if any problems.
