### ISSUE TITLE
unable to view radar chart in shiny server

### ISSUE THREAD

**Issue by bansaliti** [MangoTheCat/radarchart#35]
Shiny web app shows radar chart on windows but after hosting to server it doesnot show the chart without any error

**Comment by RudyMartin** [comment]
Me too!! When I go to add this to shiny it is looking for something that has changed or missing.

  building: Fetching packages
  error: Building package: radarchart
################################ Begin Task Log ################################ 
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 254065610 failed: Error building image: Error fetching radarchart (0.2.0) source. Error accessing GitHub repository MangoTheCat/radarchart. HTTP 401: Unauthorized
Execution halted

**Comment by dougmet** [comment]
Hi,

@bansaliti Is this an error once the Shiny app is up and running? I need a little more before I can diagnose. I admit I've not used it on Shiny Server before.

@RudyMartin this looks like you're having trouble installing the package. Have you been able to install other github packages in the past?
