### ISSUE TITLE
Couldn't Resolve Host Name

### ISSUE THREAD

**Issue by jasonchanhku** [MangoTheCat/radarchart#38]
Hi Doug,

Thanks for the awesome update for this package. However, I tried installing the latest version from github and I get the following error:

> devtools::install_github("MangoTheCat/radarchart")
**Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't resolve host name**

**Comment by jasonchanhku** [comment]
solved. used CRAN instead.

**Comment by dougmet** [comment]
Glad you've found a way around. I think curl errors are more likely a connection issue but let me know if it's only radarchart you can't get from github.

**Comment by jasonchanhku** [comment]
No worries, all is good now. Thanks again for taking your time to develop this, you have no idea how many lives it saved :) Cheers buddy !
