### ISSUE TITLE
Warning: Error in .subset: invalid subscript type 'list'

### ISSUE THREAD

**Issue by tokumotion** [MangoTheCat/radarchart#4]
Hi!

Thank you for the library! 

I've tried to run an exercise to test things out [in this repository](https://github.com/tokumotion/GCI_Data), but I am encountering an error when running `chartJSRadarOutput()`.

The error I get is:

```
Listening on http://127.0.0.1:6193
Warning: Error in .subset: invalid subscript type 'list'
Stack trace (innermost first):
    71: [.tbl_df
    70: [
    69: chartJSRadar
    68: func [/Users/jramirezcastillo/GitHub/GCI_Data/R Files/server.R#13]
    67: output$MyPlot
     1: runApp
```

When I run the `chartJSRadar()` function alone, it renders the radar plot correctly. Problem is when I try to send the plot to `ui.R` in the shiny app.

The code I get the error from is [here](https://github.com/tokumotion/GCI_Data/tree/master/R%20Files). I'm sorry if I am such a bother but I'd really like you to check this very basic shiny app and point me towards the error.

**Comment by dougmet** [comment]
Looks like your `reactive` block needs to be in server.R. I've sent a PR with the necessary changes. Also, see #3 for some useful options in Shiny. I'll make these settings default in the next version.

**Comment by tokumotion** [comment]
Thank you @dougmet ! So I always need to declare the size of the widget in order to render?

**Comment by dougmet** [comment]
Great news. I've updated the default sizing on GitHub but in the mean time it's best to override the defaults. It always rendered it just got the aspect ratio all wrong.
