### ISSUE TITLE
radarchart renders wrong chart when pass mouse over it in local

### ISSUE THREAD

**Issue by tokumotion** [MangoTheCat/radarchart#8]
Hi!

When rendering chart in shiny, every time I pass the mouse over some parts of the chart, it displays the wrong data. I think it displays the first data set it rendered in the app.

You can check the error if you run the app in your local machine [here](https://github.com/tokumotion/GCI_Data)

Thank you!

**Comment by dougmet** [comment]
Do you mean the tool tip data? By eye it looks about right to me. If you're able to make a minimal example that'd be really helpful.

**Comment by tokumotion** [comment]
Ok, I recorded it for you [here](http://screencast.com/t/wOFPQx7MNA). Hope it helps.

Maybe it's my RStudio version?

**Comment by dougmet** [comment]
Hi, sorry if I'm being dumb but I've had a good look at the video and I'm not sure where it's rendering the wrong data (I'm not familiar with your data set). I'm wondering if this is an issue with the app rather than radarchart?
